apiVersion: v1
kind: Secret
metadata:
  name: sample-database-auth-key
stringData:
  SQLD_AUTH_JWT_KEY: 6oPtG2exf8zRDMdhIbcB5Nlor6ipAG3bHipp7u_XawU
---
apiVersion: v1
kind: Service
metadata:
  name: sample-database-primary
  namespace: default
  labels:
    app: sample-database
    node: primary
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: primary-http
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: primary-grpc
  clusterIP: None
  selector:
    app: sample-database
    node: primary
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sample-database
    node: primary
  name: sample-database-primary
  namespace: default
spec:
  selector:
    matchLabels:
      app: sample-database
      node: primary
  serviceName: "sample-database-primary"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: sample-database
        node: primary
    spec:
      containers:
        - image: ghcr.io/tursodatabase/libsql-server:v0.24.21
          name: libsql-server
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          ports:
            - containerPort: 8080
              protocol: TCP
              name: primary-http
            - containerPort: 5001
              protocol: TCP
              name: primary-grpc
          env:
            - name: SQLD_NODE
              value: primary
            - name: SQLD_AUTH_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: sample-database-auth-key
                  key: SQLD_AUTH_JWT_KEY
          volumeMounts:
            - name: sample-database-pvc
              mountPath: /var/lib/sqld
  volumeClaimTemplates:
    - metadata:
        name: sample-database-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sample-database-replica
  namespace: default
  labels:
    app: sample-database
    node: replica
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: replica-http
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: replica-grpc
  clusterIP: None
  selector:
    app: sample-database
    node: replica
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sample-database
    node: replica
  name: sample-database-replica
  namespace: default
spec:
  selector:
    matchLabels:
      app: sample-database
      node: replica
  serviceName: "sample-database-replica"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: sample-database
        node: replica
    spec:
      containers:
        - image: ghcr.io/tursodatabase/libsql-server:v0.24.21
          name: libsql-server
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          ports:
            - containerPort: 8080
              protocol: TCP
              name: replica-http
            - containerPort: 5001
              protocol: TCP
              name: replica-grpc
          env:
            - name: SQLD_NODE
              value: replica
            - name: SQLD_PRIMARY_URL
              value: http://sample-database-primary-0.sample-database-primary:5001
            - name: SQLD_AUTH_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: sample-database-auth-key
                  key: SQLD_AUTH_JWT_KEY
          volumeMounts:
            - name: sample-database-pvc
              mountPath: /var/lib/sqld
  volumeClaimTemplates:
    - metadata:
        name: sample-database-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sample-database
  namespace: default
  labels:
    app: sample-database
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: grpc
  selector:
    app: sample-database
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-database-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ahti.database.com
      secretName: secret-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-database
                port:
                  number: 8080


