apiVersion: v1
kind: Secret
metadata:
  name: sample-database-auth-key
stringData:
  PUBLIC_KEY: 8EmDxCXOuCcL9y3aF-tMJI5jb8JWP0Bm26c4O9rw34o
  PRIVATE_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1DNENBUUF3QlFZREsyVndCQ0lFSUphWnZQMkFPdkQ1OWlEWFQzZ0gzUm01b2o4WFNVWWtwMnZqbE1tWTBjc3cKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo
---
apiVersion: v1
kind: Service
metadata:
  name: sample-database-svc-headless
  namespace: default
  labels:
    ahti.database.io/managed-by: sample-database
    node: primary
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: primary-http
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: primary-grpc
  clusterIP: None
  selector:
    ahti.database.io/managed-by: sample-database
    node: primary
---
apiVersion: v1
kind: Service
metadata:
  name: sample-database-svc
  namespace: default
  labels:
    ahti.database.io/managed-by: sample-database
    node: primary
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: primary-http
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: primary-grpc
  selector:
    ahti.database.io/managed-by: sample-database
    node: primary
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    ahti.database.io/managed-by: sample-database
    node: primary
  name: sample-database
  namespace: default
spec:
  selector:
    matchLabels:
      ahti.database.io/managed-by: sample-database
      node: primary
  serviceName: "sample-database-svc-headless"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        ahti.database.io/managed-by: sample-database
        node: primary
    spec:
      containers:
        - image: ghcr.io/tursodatabase/libsql-server:v0.24.21
          name: libsql-server
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          ports:
            - containerPort: 8080
              protocol: TCP
              name: primary-http
            - containerPort: 5001
              protocol: TCP
              name: primary-grpc
          env:
            - name: SQLD_NODE
              value: primary
            - name: SQLD_AUTH_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: sample-database-auth-key
                  key: PUBLIC_KEY
          volumeMounts:
            - name: sample-database-pvc
              mountPath: /var/lib/sqld
  volumeClaimTemplates:
    - metadata:
        name: sample-database-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
