apiVersion: libsql.ahti.io/v1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: ahti-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample-database
  namespace: default
spec:
  image: ghcr.io/tursodatabase/libsql-server:v0.24.21
  imagePullPolicy: Always
  auth: true
  storage:
    size: 1Gi
  resources:
    requests:
      memory: "200Mi"
      cpu: "200m"
    limits:
      memory: "200Mi"
      cpu: "200m"
  ingress:
    ingressClassName: nginx
    host: ahti.database.com
    tls:
    - hosts:
        - ahti.database.com
      secretName: secret-tls
