apiVersion: libsql.ahti.io/v1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: ahti-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample-database
  namespace: default
spec:
  image: ghcr.io/tursodatabase/libsql-server:v0.24.21
  # optional default IfNotPresent
  imagePullPolicy: Always
  # optional
  # ImagePullSecrets: []
  auth: false
  storage:
    size: 1Gi
  env:
    - name: HELLO
      value: world
  # optional
  resources:
    requests:
      memory: "200Mi"
      cpu: "200m"
    limits:
      memory: "200Mi"
      cpu: "200m"
  # optional
  # NodeSelector:
  # optional
  # ServiceAccountName:
  # optional
  # AutomountServiceAccountToken:
  # optional
  # Affinity:
  # optional
  # SchedulerName:
  # optional
  # Tolerations: []
  # optional
  ingress:
    ingressClassName: nginx
    host: ahti.database.io
    # tls:
    # - hosts:
    #     - ahti.database.io
    #   secretName: secret-tls
